SELECT CAR_ID,CAR_TYPE, ROUND(FEE) AS FEE
FROM
    (
        SELECT AA.CAR_ID, AA.CAR_TYPE, AA.DAILY_FEE,
               (AA.DAILY_FEE * (100-CAST(REPLACE(BB.DISCOUNT_RATE,'%','') AS FLOAT))*0.01 *30) AS FEE
        FROM (
                 SELECT CAR_ID, CAR_TYPE, DAILY_FEE
                 FROM CAR_RENTAL_COMPANY_CAR A
                 WHERE CAR_TYPE IN ('세단','SUV')
                   AND CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                                      WHERE START_DATE>='2022-11-01' AND END_DATE<='2022-11-30')
                 GROUP BY CAR_ID, CAR_TYPE, DAILY_FEE
             ) AA JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN BB
                       ON AA.CAR_TYPE = BB.CAR_TYPE
        WHERE BB.DURATION_TYPE='30일 이상'
    ) AAA
WHERE FEE > 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID ASC